# Generated by Django 4.2 on 2024-01-02 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_profile_bio_profile_birth_date_profile_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
