# Generated by Django 4.2 on 2024-01-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0009_profile_date_modified_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
